name: l3das22
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - absl-py=0.15.0=pyhd3eb1b0_0
  - aiohttp=3.6.3=py38h7b6447c_0
  - async-timeout=3.0.1=py38h06a4308_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py38h06a4308_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2021.10.26=h06a4308_2
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.10.8=py38h06a4308_2
  - cffi=1.15.0=py38hd667e15_1
  - chardet=3.0.4=py38h06a4308_1003
  - click=8.0.3=pyhd3eb1b0_0
  - cryptography=3.4.8=py38hd23ed53_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dataclasses=0.8=pyh6d0b6a4_7
  - gmp=6.2.1=h2531618_2
  - gmpy2=2.0.8=py38hd5f6e3b_3
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.42.0=py38hce63b2e_0
  - h5py=2.10.0=py38hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.8.2=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libprotobuf=3.19.1=h4ff587b_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libuv=1.40.0=h7b6447c_0
  - markdown=3.3.4=py38h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py38h06a4308_0
  - multidict=4.7.6=py38h7b6447c_1
  - ncurses=6.3=h7f8727e_2
  - numpy=1.20.1=py38h93e21f0_0
  - numpy-base=1.20.1=py38h7d8b39e_0
  - oauthlib=3.2.0=pyhd3eb1b0_0
  - openssl=1.1.1m=h7f8727e_0
  - pandas=1.2.4=py38h2531618_0
  - pip=21.2.4=py38h06a4308_0
  - protobuf=3.19.1=py38h295c915_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.1.0=py38h06a4308_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.8=hdb3f193_5
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.10.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pyyaml=6.0=py38h7f8727e_1
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - ruamel.yaml=0.16.12=py38h7b6447c_1
  - ruamel.yaml.clib=0.2.6=py38h7f8727e_0
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.37.2=hc218d9a_0
  - sympy=1.8=py38h06a4308_0
  - tensorboard=2.6.0=py_1
  - tensorboard-data-server=0.6.0=py38hca6d32c_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - termcolor=1.1.0=py38h06a4308_1
  - tk=8.6.11=h1ccaba5_0
  - tqdm=4.59.0=pyhd3eb1b0_1
  - typing_extensions=4.1.1=pyha770c72_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.3=py38h27cfd23_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - appdirs==1.4.4
    - audioread==2.1.9
    - charset-normalizer==2.0.12
    - joblib==1.1.0
    - librosa==0.8.1
    - llvmlite==0.38.0
    - numba==0.55.1
    - pooch==1.6.0
    - resampy==0.2.2
    - ruamel-base==1.0.0
    - scikit-learn==1.0.2
    - soundfile==0.10.3.post1
    - threadpoolctl==3.1.0
prefix: <Your Anaconda envs folder> # /home/hjb/anaconda3/envs/l3das22
